#!/bin/bash
roslaunch suturo_knowledge_location mapserver_lab.launch &
rosrun SnapMapICP SnapMapICP &
rosrun suturo_knowledge_location LocationPublisher &
trap 'kill $(jobs -p)' EXIT
for job in `jobs -p`
do
wait $job
done
